apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-downloader-config
  namespace: movie-downloader
data:
  HOST: "0.0.0.0"
  PORT: "3001"
  DOWNLOADS_PATH: "/downloads"
  TRANSMISSION_HOST: "transmission"
  TRANSMISSION_PORT: "9091"
  MIN_TO_DELETION: "1440"
  GUEST_MIN_TO_DELETION: "240"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  MAIL_FROM: "Movie Downloader <goransmoviedownloader@gmail.com>"
  PUBLIC_API_URL: "https://api.moviedownloader.gorantopic.com"
