apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-downloader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GoranTopic/movie-downloader.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: movie-downloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
